spring:
  application:
    name: peer-registry
eureka:
  instance:
    appname: peer-registry
peer:
  default:
    host: localhost
    port: 8762
  vcloud:
    host: peer-vcloud
    port: 8761
  azure:
    host: peer-azure
    port: 8762

---
spring:
  profiles: default
server:
  port: ${peer.default.port}
eureka:
  instance:
    hostname: ${peer.default.host}
  client:
    fetchRegistry: false
    registerWithEureka: false

---
spring:
  profiles: vcloud
server:
  port: ${peer.vcloud.port}
eureka:
  instance:
    hostname: ${peer.vcloud.host}
  client:
    serviceUrl:
      defaultZone: http://${peer.azure.host}:${peer.azure.port}/eureka
    fetchRegistry: true
    registerWithEureka: true

---
spring:
  profiles: azure
server:
  port: ${peer.azure.port}
eureka:
  instance:
    hostname: ${peer.azure.host}
  client:
    serviceUrl:
      defaultZone: http://${peer.vcloud.host}:${peer.vcloud.port}/eureka
    fetchRegistry: true
    registerWithEureka: true